# Generated by Django 4.2.7 on 2023-12-09 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbox', '0002_remove_scrapbox_user_userprofile_posts_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='block',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='following',
        ),
    ]
