# Generated by Django 4.2.7 on 2023-12-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbox', '0005_rename_address_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapbox',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
