# Generated by Django 4.2.7 on 2024-01-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbox', '0006_scrapbox_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapbox',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
