# Generated by Django 4.2.7 on 2024-01-16 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbox', '0009_basket_delete_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapbox',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitem', to='scrapbox.basket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapbox.scrapbox')),
            ],
        ),
    ]
