# Generated by Django 4.2.7 on 2024-01-19 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrapbox', '0010_alter_scrapbox_description_basketitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='basket',
            name='scrap',
            field=models.ManyToManyField(related_name='wished_scrap', to='scrapbox.scrapbox'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
