# Generated by Django 4.2.7 on 2024-01-19 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrapbox', '0011_remove_basket_is_active_remove_basket_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='owner',
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_whishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
