# Generated by Django 4.2.7 on 2024-01-19 18:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrapbox', '0012_remove_basket_owner_basket_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basket',
            new_name='WishList',
        ),
    ]
