# Generated by Django 4.2.7 on 2024-03-15 04:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrapbox', '0016_remove_cartitem_cart_alter_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishList',
            new_name='CartList',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
