# Generated by Django 4.2.7 on 2024-03-15 04:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrapbox', '0017_rename_wishlist_cartlist_remove_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartList',
            new_name='WishList',
        ),
    ]
