# Generated by Django 4.2.7 on 2024-03-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbox', '0020_shipping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='adrress',
            new_name='address',
        ),
    ]
